"""Update

Revision ID: 00669f0aa58d
Revises: 7b85807a2051
Create Date: 2024-10-12 12:33:56.997393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00669f0aa58d'
down_revision = '7b85807a2051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path_input', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_path_output', sa.String(), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('file_path_output')
        batch_op.drop_column('file_path_input')

    # ### end Alembic commands ###
